name: Execute On Schedule

on:
  schedule:
    - cron: '0 * * * *'  # Executes at minute 0 of every hour
  workflow_dispatch:

permissions:
  contents: write  # این خط برای فعال‌سازی push با GITHUB_TOKEN داخلی الزامی است

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository Contents
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Python Packages Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute Python Script
        run: python main.py
          
      - name: Commit Files
        run: |
          git config --local user.email "seyyedsoroushmirzaei@protonmail.com"
          git config --local user.name "Soroush Mirzaei"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Updated $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M %Z')" --allow-empty)
          
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
